### ISSUE TITLE
Save state used jquery-cookie

### ISSUE THREAD

**Issue by Alex-Sokolov** [rstaib/jquery-steps#136]
jQuery-steps using jquery.cookies plugin when check saveState option:

``` js
 // Tries to load the saved state (step position)
    if (options.saveState && $.cookie)
    {
        var savedState = $.cookie(_cookiePrefix + getUniqueId(wizard));
        // Sets the saved position to the start index if not undefined or out of range 
        var savedIndex = parseInt(savedState, 0);
        if (!isNaN(savedIndex) && savedIndex < state.stepCount)
        {
            startIndex = savedIndex;
        }
    }
```

But now, new version of jquery-cookies now is js-cookies with new syntax, json support and dependency free: on top important note https://github.com/carhartl/jquery-cookie

**Comment by pabloselin** [comment]
It would be nice to have support for the new, improved js-cookie

**Comment by abstractindia** [comment]
I want to preserve the step on page refresh. How can it be done using saveState?

**Comment by angeloimm** [comment]
You can give a look here http://www.jeffmould.com/2016/02/14/jquery-steps-plugin-savestate-js-cookie/
It would be good to have it in newer version of jquery steps and to have a method to delete the cookie since I had to delete it manually in the onFinished event and by creating manually the cookie name
