### ISSUE TITLE
If select(dropdown) val = "something", insert step

### ISSUE THREAD

**Issue by rhoffman2193** [rstaib/jquery-steps#164]
Basically I'm trying to have it that if someone chooses a position of "driver" it'll insert a driver application section of an employment application. I tried this (note this is inside a php document that's why there's php variables): 

$('select[name="position-desired"]').change(function(){
            if($(this).val()=="Driver"){
                <?php $driver = "yes"; ?>
            } else {
                <?php $driver = "no"; ?>
            }
        });

And inside of a php if statement if($driver == "yes"): echo the section, else don't.

Anyone have an idea on how this could be done differently? What I'm doing currently isn't working (obviously).

**Comment by alif1982** [comment]
If you are assigning the onchange handler for your "select" control before initializing the steps control your code will not work, try to add it after and it will work.

and if you want to know the reason, the steps plugin removes all of the html and re-add it to the page again after applying some modifications, that's why your dropdown list is not working
