### ISSUE TITLE
Is there a way to add 3rd button along side Previous and Next?

### ISSUE THREAD

**Issue by frostshoxx** [rstaib/jquery-steps#210]
I would like to add extra button along side the Next and Previous button that perform different action other than going back and forth between the wizard section, such as open up help pop up, call a function that save the form, clear all fields, etc.

Is there a way to do that with the current features? 

Thank you,

**Comment by alicansoysal** [comment]
just add this line to your steps setting:
`enablePagination: false,`

and create your **next** button: #right 
`$(document).delegate('#right', 'click', function(){
    var a = $(".wizard").steps("next");
    if(!a){
      $(".wizard").steps("finish");
    }
  });`

**Comment by frostshoxx** [comment]
Thank you for the reply. 

Just to clarify, I'm looking for the third button to be put alongside the Previous and Next buttons. Would `$(document).delegate('#someName', 'click', function() {...});` be the syntax use for creating a new button?

**Comment by azizimusa** [comment]
you can do like this too:

`var $input = $('<button>My new Button</button>');`
            
`$input.appendTo($('ul[aria-label=Pagination]'));`

**Comment by frostshoxx** [comment]
@azizimusa Thanks for sharing! I end up doing something similar to that as well.

**Comment by vagi8** [comment]
I got more sophisticated solution. You only need to add 5 lines of code to the existing **jquery.steps.js** file. Although a bit long (than what @azizimusa 's solution) it will never escape the steps functionality. so it will be more iron clad. If you want to add a new button (which is not previous or next or finish), -
I ll be taking with an example. Lets say, i want to add an extra button "Save Draft" specifically to final step. 

**All this code will be available in the jquery.steps.js**
**All the code lines between '\*\*' are lines i have added to the existing functions ** 

1. The first thing you might want to do is to add it to the view of pagination. 
    
        function renderPagination(wizard, options, state)
       {
             if (options.enablePagination)
        {    
        var pagination = "<{0} class=\"actions {1}\"><ul role=\"menu\" aria-label=\"{2}\">{3}</ul></{0}>",     
        buttons = "";

        if (!options.forceMoveForward)
        {
            buttons += buttonTemplate.format("previous", options.labels.previous);
        }

        buttons += buttonTemplate.format("next", options.labels.next);

        if (options.enableFinishButton)
        {
            buttons += buttonTemplate.format("finish", options.labels.finish);
            **buttons += buttonTemplate.format("save_draft", 'Save Draft');**
        }

        if (options.enableCancelButton)
        {
            buttons += buttonTemplate.format("cancel", options.labels.cancel);
        }

        wizard.append(pagination.format(options.actionContainerTag, options.clearFixCssClass,
            options.labels.pagination, buttons));

        refreshPagination(wizard, options, state);
        loadAsyncContent(wizard, options, state);
       }
       }

I have added the new button to enableFinishButton if loop.
The "save_draft"  which will be the href of the anchor of our new button. Which will tell pagination which function to run on clicking. 
**NOTE**: doing only this step will add the button to all the steps. Do the point 5 to limit the new button to only Finish step. 

2. Next for the step to know which function to redirect to, we will add it to switch cases which is ...

`
    

     function paginationClickHandler(event)
     {
     event.preventDefault();
     var anchor = $(this),
        wizard = anchor.parent().parent().parent().parent(),
        options = getOptions(wizard),
        state = getState(wizard),
        href = anchor.attr("href");

    switch (href.substring(href.lastIndexOf("#") + 1))
    {
        case "cancel":
            cancel(wizard);
            break;

        case "finish":
            finishStep(wizard, state);
            break;
        **case "save_draft":
            SaveDraftStep(wizard, state);
            break;**
        case "next":
            goToNextStep(wizard, options, state);
            break;

        case "previous":
            goToPreviousStep(wizard, options, state);
            break;
      }
      }`

note that i have written a new _save_draft_ CASE which was not present previously. This case will tell the jquery to go to the _SaveDraftStep_ function. writing that will be our next point.

3. 
`
     

     function SaveDraftStep(wizard,state)
     {
     var currentStep = wizard.find(".steps li").eq(state.currentIndex);
     if (wizard.triggerHandler("finishing", [state.currentIndex]))
    {
        currentStep.addClass("done").removeClass("error");
        **wizard.triggerHandler("savedraft", [state.currentIndex]);**
    }
    else
    {
        currentStep.addClass("error");
    }
    }
`
**NOTE**: More caution required in this step. if you fuck this jquery will fuck you.
**NOTE**: i have the entire function lines of _function finishStep_ so that i dont kill the jquery.
Please give attention to the _wizard.triggerHandler("savedraft", [state.currentIndex]);_ line. which will trigger the function with name (not exactly the same name) **_savedraft_**

_EXTRAS_ : what this function originally does it to execute when the button is clicked in the final step (hence the name finalStep)

4. Now all we need to do is write the function. But HOLD. As i said above, we wont giving the name "savedraft" to our function. 
         we have to register this event functionin the below function. 
`
     

     function registerEvents(wizard, options)
    {
    var eventNamespace = getEventNamespace(wizard);
    wizard.bind("canceled" + eventNamespace, options.onCanceled);
    wizard.bind("contentLoaded" + eventNamespace, options.onContentLoaded);
    wizard.bind("finishing" + eventNamespace, options.onFinishing);
    wizard.bind("finished" + eventNamespace, options.onFinished);
    **wizard.bind("savedraft" + eventNamespace, options.onSaveDraft);**
    wizard.bind("init" + eventNamespace, options.onInit);
    wizard.bind("stepChanging" + eventNamespace, options.onStepChanging);
    wizard.bind("stepChanged" + eventNamespace, options.onStepChanged);

    if (options.enableKeyNavigation)
    {
        wizard.bind("keyup" + eventNamespace, keyUpHandler);
    }

    wizard.find(".actions a").bind("click" + eventNamespace, paginationClickHandler);
    }
`
**_options.onSaveDraft_** will be our new function which we will be called finally and write your new button logic.
This new function can be written where you mention the other similar functions like _onStepChanging_ _onFinished_ _onFinishing_ (This actually where the option of the jquery steps are written.) This new function can also be written where you define the wizard step and options. 

5. Remember i mentioned in the first point that this new button added will be available in all the steps. If you want to restrict that to only the final step follow along this final step, otherwise Bye Bye. Thanks for reading this awfully long comment. 

There is _refreshPagination_ function which will define what pagination (button) should be there in which step.

`

        function refreshPagination(wizard, options, state)
        {
        if (options.enablePagination)
        {
        var finish = wizard.find(".actions a[href$='#finish']").parent(),
            **save = wizard.find(".actions a[href$='#save_draft']").parent(),**
            next = wizard.find(".actions a[href$='#next']").parent();
        if (!options.forceMoveForward)
        {
            var previous = wizard.find(".actions a[href$='#previous']").parent();
            previous._enableAria(state.currentIndex > 0);
        }

        if (options.enableFinishButton && options.showFinishButtonAlways)
        {
            finish._enableAria(state.stepCount > 0);
            next._enableAria(state.stepCount > 1 && state.stepCount > (state.currentIndex + 1));
        }
        else
        {
            finish._showAria(options.enableFinishButton && state.stepCount === (state.currentIndex + 1));
            **save._showAria(options.enableFinishButton && state.stepCount === (state.currentIndex + 1));**
            next._showAria(state.stepCount === 0 || state.stepCount > (state.currentIndex + 1)).
                _enableAria(state.stepCount > (state.currentIndex + 1) || !options.enableFinishButton);
        }
    }
}`
First i have created a new variable save (similar to finish). Then in the if else loop, i have placed in the else. cause thats where i need it to be.  For your own customization, you can write your own elif as well.
Thats it. Go now. bye bye.

**Comment by suvin94** [comment]
> you can do like this too:
> 
> `var $input = $('<button>My new Button</button>');`
> 
> `$input.appendTo($('ul[aria-label=Pagination]'));`

This helped me on 2020. Thanks Man !
